-- Asterion combined schema — paste into Supabase SQL editor (Dashboard > SQL Editor > New query).
-- Order matters; run the whole file once.

-- ============================================================
-- migrations/0001_content.sql
-- ============================================================
-- Content tables: novels + chapters.
-- Mirrors asterion-scraper/models/Novel.ts initializeSchema() exactly so the
-- ported Rust scraper can upsert with identical semantics.

create extension if not exists pg_trgm;

create table if not exists public.novels (
  id              bigint generated by default as identity primary key,
  title           text not null,
  novel_url       text unique,
  author          text,
  rank            text,
  total_chapters  text,
  views           text,
  bookmarks       text,
  status          text,
  genres          text[] not null default '{}',
  summary         text,
  chapters_url    text,
  image_url       text,
  rating          double precision,
  last_scraped    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint rating_range check (rating is null or (rating >= 0 and rating <= 10))
);

-- Chapter INDEX only — the bulk chapter text lives in Google Cloud Storage.
-- `content_path` is the GCS object path (e.g. novels/<slug>/chapter-<n>.txt);
-- the reader builds the public URL from the configured bucket.
create table if not exists public.chapters (
  id              bigint generated by default as identity primary key,
  novel_id        bigint not null references public.novels(id) on delete cascade,
  chapter_number  integer not null,
  url             text not null unique,
  title           text not null,
  content_path    text not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (novel_id, chapter_number)
);

create index if not exists idx_chapters_novel_id on public.chapters (novel_id);

-- Trigram index for catalog search (title).
create index if not exists idx_novels_title_trgm on public.novels using gin (title gin_trgm_ops);

-- keep updated_at fresh on any row update
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_novels_touch on public.novels;
create trigger trg_novels_touch before update on public.novels
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_chapters_touch on public.chapters;
create trigger trg_chapters_touch before update on public.chapters
  for each row execute function public.touch_updated_at();


-- ============================================================
-- migrations/0002_user_data.sql
-- ============================================================
-- Per-user reading data. user_id = auth.uid() (anonymous sessions are fine).
-- Extends asterion-ios backend/drizzle (0001_add_user_preferences.sql) with the
-- reader settings the desktop ReaderView needs (theme, font size, spacing, width).

create table if not exists public.reading_progress (
  user_id      uuid not null references auth.users(id) on delete cascade,
  novel_id     bigint not null references public.novels(id) on delete cascade,
  chapter_id   bigint not null references public.chapters(id) on delete cascade,
  current_line integer not null default 0,
  total_lines  integer not null default 1,
  updated_at   timestamptz not null default now(),
  primary key (user_id, novel_id)
);
create index if not exists idx_reading_progress_user on public.reading_progress (user_id);

create table if not exists public.library (
  user_id    uuid not null references auth.users(id) on delete cascade,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  added_at   timestamptz not null default now(),
  primary key (user_id, novel_id)
);

create table if not exists public.bookmarks (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  line       integer not null default 0,
  note       text,
  created_at timestamptz not null default now(),
  unique (user_id, chapter_id, line)
);
create index if not exists idx_bookmarks_user on public.bookmarks (user_id);

create table if not exists public.user_preferences (
  user_id          uuid primary key references auth.users(id) on delete cascade,
  reading_goal     integer not null default 30,
  theme            text not null default 'dark'
                     check (theme in ('dark','light','sepia','warm')),
  font_size        integer not null default 19 check (font_size between 12 and 32),
  line_spacing     double precision not null default 0.85,
  max_width        integer not null default 780,
  font_family      text not null default 'serif' check (font_family in ('serif','sans')),
  notifications_on boolean not null default true,
  updated_at       timestamptz not null default now()
);

-- touch updated_at
drop trigger if exists trg_progress_touch on public.reading_progress;
create trigger trg_progress_touch before update on public.reading_progress
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_prefs_touch on public.user_preferences;
create trigger trg_prefs_touch before update on public.user_preferences
  for each row execute function public.touch_updated_at();


-- ============================================================
-- migrations/0003_rls.sql
-- ============================================================
-- Row Level Security.
-- Content (novels/chapters): world-readable; NO insert/update/delete policy for
-- anon or authenticated, so only the service_role (which bypasses RLS, used by
-- the ingest-novel Edge Function) can write. The client never gets a write key.
-- User data: each row is private to its owner (auth.uid()).

alter table public.novels   enable row level security;
alter table public.chapters enable row level security;

drop policy if exists "novels read" on public.novels;
create policy "novels read" on public.novels
  for select to anon, authenticated using (true);

drop policy if exists "chapters read" on public.chapters;
create policy "chapters read" on public.chapters
  for select to anon, authenticated using (true);

-- ---- user-scoped tables ----
alter table public.reading_progress enable row level security;
alter table public.library          enable row level security;
alter table public.bookmarks        enable row level security;
alter table public.user_preferences enable row level security;

-- reading_progress
drop policy if exists "own progress" on public.reading_progress;
create policy "own progress" on public.reading_progress
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- library
drop policy if exists "own library" on public.library;
create policy "own library" on public.library
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- bookmarks
drop policy if exists "own bookmarks" on public.bookmarks;
create policy "own bookmarks" on public.bookmarks
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- user_preferences
drop policy if exists "own prefs" on public.user_preferences;
create policy "own prefs" on public.user_preferences
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- migrations/0004_scrape_requests.sql
-- ============================================================
-- Desktop users can request a novel that isn't scraped yet. The VM catalog
-- runner (`catalog-runner queue`) drains this table and scrapes the novels.

create table if not exists public.scrape_requests (
  id           bigint generated by default as identity primary key,
  novel_url    text not null,
  status       text not null default 'pending'
                 check (status in ('pending','processing','done','error')),
  requested_by uuid references auth.users(id) on delete set null,
  created_at   timestamptz not null default now(),
  processed_at timestamptz
);

-- one open request per URL at a time
create unique index if not exists uniq_pending_request
  on public.scrape_requests (novel_url)
  where status in ('pending', 'processing');

create index if not exists idx_scrape_requests_status on public.scrape_requests (status);

alter table public.scrape_requests enable row level security;

-- Authenticated users may file a request and see request status; the service
-- role (VM) updates rows (bypasses RLS).
drop policy if exists "insert own request" on public.scrape_requests;
create policy "insert own request" on public.scrape_requests
  for insert to authenticated
  with check (auth.uid() = requested_by);

drop policy if exists "read requests" on public.scrape_requests;
create policy "read requests" on public.scrape_requests
  for select to authenticated using (true);




-- ============ 0005_rankings.sql ============
-- External ranking lists scraped from webnoveldb.com (a WordPress novel
-- aggregator). Each row is one ranked title in a category; novel_id links it to
-- our novelfire catalog when a title match exists (NULL = we don't have it, the
-- UI greys it out). The VM replaces a category's rows on each scrape.

create table if not exists public.rankings (
  category    text   not null,            -- trending | daily | editors_choice | weekly | monthly | alltime
  position    integer not null,           -- 1-based rank within the category
  source_slug text   not null,            -- webnoveldb /novel/{slug}
  source_url  text   not null,
  title       text   not null,
  cover_url   text,
  novel_id    bigint references public.novels(id) on delete set null,
  scraped_at  timestamptz not null default now(),
  primary key (category, position)
);

create index if not exists idx_rankings_category on public.rankings (category, position);
create index if not exists idx_rankings_novel on public.rankings (novel_id);

alter table public.rankings enable row level security;

-- Read-all (anon + authenticated); writes are service-role only (the VM).
drop policy if exists rankings_read on public.rankings;
create policy rankings_read on public.rankings
  for select to anon, authenticated using (true);


-- ============ 0006_comments.sql ============
-- Novel comments scraped (read-only) from novelfire's /comment/show endpoint.
-- source_id = novelfire's data-comid, so re-scrapes dedupe instead of pile up.

create table if not exists public.comments (
  id         bigint generated by default as identity primary key,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  source_id  text not null,
  author     text,
  avatar_url text,
  body       text not null,
  posted_at  text,             -- relative label as shown on novelfire ("12m", "3d")
  likes      integer not null default 0,
  scraped_at timestamptz not null default now(),
  unique (novel_id, source_id)
);

create index if not exists idx_comments_novel on public.comments (novel_id, id desc);

alter table public.comments enable row level security;

-- Read-all (anon + authenticated); writes are service-role only (the VM).
drop policy if exists comments_read on public.comments;
create policy comments_read on public.comments
  for select to anon, authenticated using (true);


-- ============ 0007_scrape_progress.sql ============
-- Aggregate scrape-progress counters, exposed as a single-row view so the app
-- can show live progress with the publishable key (read-only). Runs as the view
-- owner, so the distinct-novel counts work regardless of per-table RLS.

create or replace view public.scrape_progress as
select
  (select count(*) from public.novels)                              as novels_total,
  (select count(*) from public.novels where image_url is not null)  as novels_enriched,
  (select count(distinct novel_id) from public.chapters)            as novels_with_chapters,
  (select count(*) from public.chapters)                            as chapters_total,
  (select count(distinct novel_id) from public.comments)           as novels_with_comments,
  (select count(*) from public.comments)                            as comments_total,
  (select count(*) from public.scrape_requests where status = 'pending')    as queue_pending,
  (select count(*) from public.scrape_requests where status = 'processing') as queue_processing;

grant select on public.scrape_progress to anon, authenticated;


-- ============ 0008_hide_progress.sql ============
-- Hide scrape internals from the public REST surface. The app reads
-- scrape_progress over an *authenticated* anonymous session (role
-- `authenticated`), so the owner's admin dashboard keeps working; revoking
-- `anon` blocks reads made with only the publishable key and no session.
revoke select on public.scrape_progress from anon;
