-- Content tables: novels + chapters.
-- Mirrors asterion-scraper/models/Novel.ts initializeSchema() exactly so the
-- ported Rust scraper can upsert with identical semantics.

create extension if not exists pg_trgm;

create table if not exists public.novels (
  id              bigint generated by default as identity primary key,
  title           text not null,
  novel_url       text unique,
  author          text,
  rank            text,
  total_chapters  text,
  views           text,
  bookmarks       text,
  status          text,
  genres          text[] not null default '{}',
  summary         text,
  chapters_url    text,
  image_url       text,
  rating          double precision,
  last_scraped    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint rating_range check (rating is null or (rating >= 0 and rating <= 10))
);

-- Chapter INDEX only — the bulk chapter text lives in Google Cloud Storage.
-- `content_path` is the GCS object path (e.g. novels/<slug>/chapter-<n>.txt);
-- the reader builds the public URL from the configured bucket.
create table if not exists public.chapters (
  id              bigint generated by default as identity primary key,
  novel_id        bigint not null references public.novels(id) on delete cascade,
  chapter_number  integer not null,
  url             text not null unique,
  title           text not null,
  content_path    text not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (novel_id, chapter_number)
);

create index if not exists idx_chapters_novel_id on public.chapters (novel_id);

-- Trigram index for catalog search (title).
create index if not exists idx_novels_title_trgm on public.novels using gin (title gin_trgm_ops);

-- keep updated_at fresh on any row update
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_novels_touch on public.novels;
create trigger trg_novels_touch before update on public.novels
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_chapters_touch on public.chapters;
create trigger trg_chapters_touch before update on public.chapters
  for each row execute function public.touch_updated_at();
