-- Per-user reading data. user_id = auth.uid() (anonymous sessions are fine).
-- Extends asterion-ios backend/drizzle (0001_add_user_preferences.sql) with the
-- reader settings the desktop ReaderView needs (theme, font size, spacing, width).

create table if not exists public.reading_progress (
  user_id      uuid not null references auth.users(id) on delete cascade,
  novel_id     bigint not null references public.novels(id) on delete cascade,
  chapter_id   bigint not null references public.chapters(id) on delete cascade,
  current_line integer not null default 0,
  total_lines  integer not null default 1,
  updated_at   timestamptz not null default now(),
  primary key (user_id, novel_id)
);
create index if not exists idx_reading_progress_user on public.reading_progress (user_id);

create table if not exists public.library (
  user_id    uuid not null references auth.users(id) on delete cascade,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  added_at   timestamptz not null default now(),
  primary key (user_id, novel_id)
);

create table if not exists public.bookmarks (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  chapter_id bigint not null references public.chapters(id) on delete cascade,
  line       integer not null default 0,
  note       text,
  created_at timestamptz not null default now(),
  unique (user_id, chapter_id, line)
);
create index if not exists idx_bookmarks_user on public.bookmarks (user_id);

create table if not exists public.user_preferences (
  user_id          uuid primary key references auth.users(id) on delete cascade,
  reading_goal     integer not null default 30,
  theme            text not null default 'dark'
                     check (theme in ('dark','light','sepia','warm')),
  font_size        integer not null default 19 check (font_size between 12 and 32),
  line_spacing     double precision not null default 0.85,
  max_width        integer not null default 780,
  font_family      text not null default 'serif' check (font_family in ('serif','sans')),
  notifications_on boolean not null default true,
  updated_at       timestamptz not null default now()
);

-- touch updated_at
drop trigger if exists trg_progress_touch on public.reading_progress;
create trigger trg_progress_touch before update on public.reading_progress
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_prefs_touch on public.user_preferences;
create trigger trg_prefs_touch before update on public.user_preferences
  for each row execute function public.touch_updated_at();
