-- Desktop users can request a novel that isn't scraped yet. The VM catalog
-- runner (`catalog-runner queue`) drains this table and scrapes the novels.

create table if not exists public.scrape_requests (
  id           bigint generated by default as identity primary key,
  novel_url    text not null,
  status       text not null default 'pending'
                 check (status in ('pending','processing','done','error')),
  requested_by uuid references auth.users(id) on delete set null,
  created_at   timestamptz not null default now(),
  processed_at timestamptz
);

-- one open request per URL at a time
create unique index if not exists uniq_pending_request
  on public.scrape_requests (novel_url)
  where status in ('pending', 'processing');

create index if not exists idx_scrape_requests_status on public.scrape_requests (status);

alter table public.scrape_requests enable row level security;

-- Authenticated users may file a request and see request status; the service
-- role (VM) updates rows (bypasses RLS).
drop policy if exists "insert own request" on public.scrape_requests;
create policy "insert own request" on public.scrape_requests
  for insert to authenticated
  with check (auth.uid() = requested_by);

drop policy if exists "read requests" on public.scrape_requests;
create policy "read requests" on public.scrape_requests
  for select to authenticated using (true);
