-- Novel comments scraped (read-only) from novelfire's /comment/show endpoint.
-- source_id = novelfire's data-comid, so re-scrapes dedupe instead of pile up.

create table if not exists public.comments (
  id         bigint generated by default as identity primary key,
  novel_id   bigint not null references public.novels(id) on delete cascade,
  source_id  text not null,
  author     text,
  avatar_url text,
  body       text not null,
  posted_at  text,             -- relative label as shown on novelfire ("12m", "3d")
  likes      integer not null default 0,
  scraped_at timestamptz not null default now(),
  unique (novel_id, source_id)
);

create index if not exists idx_comments_novel on public.comments (novel_id, id desc);

alter table public.comments enable row level security;

-- Read-all (anon + authenticated); writes are service-role only (the VM).
drop policy if exists comments_read on public.comments;
create policy comments_read on public.comments
  for select to anon, authenticated using (true);
